name: Matrix Build with Scoped Variables
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]
        armbuildopt: ["-DARM"]
        x86opt: ["-Dx86"]
        
        include:
          
          
          - node-version: 18
            custom-var: ${{ matrix.armbuildopt }}
          - node-version: 16
            custom-var: ${{ matrix.x86opt }}

    steps:
      - name: Print Scoped Variable
        run: echo "Node version ${{ matrix.node-version }} - Custom Var ${{ matrix.custom-var }} matrix ${{ toJSON(matrix) }}"
