name: Matrix Build with Scoped Variables
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]
        
        include:
          - node-version: 18
            custom-var: "ARM_BUILD_OPT"
          - node-version: 16
            custom-var: "DEB"
            custom-v1: "v1"
          - node-version: 18
            custom-pkg: "DEB"

    steps:
      - name: Print Scoped Variable
        if: ${{ {matrix.custom-pkg == "DEB" || matrix.custom-var == "DEB"} && { matrix.custom-v1 == "v1"} }}      
        run: echo "Node version ${{ matrix.node-version }} - Custom Var ${{ matrix.custom-var }}"
