name: Matrix Build with Scoped Variables
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]
        custom-var: ["value-for-14", "value-for-16", "value-for-18"]
        include:
          - node-version: 14
            custom-var: "special-14"
          - node-version: 16
            custom-var: "special-16"
          - node-version: 18
            custom-var: "special-18"

    steps:
      - name: Print Scoped Variable
        run: echo "Node version ${{ matrix.node-version }} - Custom Var ${{ matrix.custom-var }}"
