name: Matrix Build with Scoped Variables
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]
        
        include:
          - armbuildopt: "-DARM"
          - x86opt: "-Dx86"
          - node-version: 18
            custom-var: "special-18"

    steps:
      - name: Print Scoped Variable
        run: echo "Node version ${{ matrix.node-version }} - Custom Var ${{ matrix.custom-var }} matrix ${{ toJSON(matrix) }}"
